### PR TITLE
added initial snapcraft file

### PR DESCRIPTION
**Pull request by manfred-kaiser**
Snapcraft can compile and run the server.

**Note:** The setup must be the same, as running the server on the host system.

**Further steps:**

- the "name" is your application name. You have to change it to something unique
- change "summary" and "description"
- to publish the snap, you need an account on https://snapcraft.io/

### CODE REVIEW

**Comment by jtesta** [comment]
Thanks for this PR.  I started testing it, though, when I found that
the "ssh-mitm" name is already taken in the Snapcraft store by your
project.  Unfortunately, this means I can't publish my own snap.  :(

**Comment by manfred-kaiser** [comment]
What do you think about ``openssh-mitm``?

**Comment by manfred-kaiser** [comment]
I have cleaned the snapcraft file. The tool now compiles without any problems.

Running seams to be a problem, because of some hardoced file paths or other problems.

For example you have a hardcoded "ssh-mitm" user. If this user does not exist on the host system, the ssh serve can not start.

I would suggest to remove this user and only check if the ssh server is not running as root. This would be sufficient.

For testing purposes, i have registered the name 'jtesta-ssh-mitm'. I have added you as collaborator. At the moment the snap is only accessible  by collaborators because I use it only for developing the snap.

What do you think about using the name "positronsecurity".

You can add multiple commands to one snap. So you can use "positronsecurity.server" to start the server. You can also add other commands: "positronsecurity.victim-finder" for your victim finder script.

Note: I have created a pip package #30 for the victim finder. This makes it easier to use it from the snap.

Would you support the snap file? If you want I can maintain the snap files for you, but I don't want to use workarounds for the snap file. So we have to add official support for snaps to the server code.

**Comment by jtesta** [comment]
I'd very much like to use the project's name as the snap package name.
 That makes the most sense for end users.  That way they can just run
"snap install ssh-mitm" and everything works as expected.

**Comment by manfred-kaiser** [comment]
i understand you, but switching the name to another project will break the installation of current users. so thats out of question.

**Comment by manfred-kaiser** [comment]
under such conditions, it's out of scope to contribute to your project

**Comment by manfred-kaiser** [comment]
i have added you as collaborator to test the snap file 'jtesta-ssh-mitm'.

You can accept the request to maintain your snap under this name.

If you are not interested, i have created a deletion request: https://forum.snapcraft.io/t/please-unregister-jtesta-ssh-mitm/25095

**Pull request closed without merging**
